version: "2.0"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
       - "80:80"
       - "443:443"
    links:
       - php
       - phpmyadmin
    volumes:
      - ./www:/var/www
      - ./hosts:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
  php:
    build: ./images/php/
    links: 
      - db
      - phpmyadmin
    volumes:
      - ./www:/var/www
  db:
    image: mysql:5.6
    container_name: database7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql_server
      MYSQL_USER: magento2
      MYSQL_PASSWORD: gotechnies
      MYSQL_ROOT_PASSWORD: gotechnies
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin7
    environment:
     - PMA_ARBITRARY=1
    restart: always
    links:
     - db
    ports:
     - 8080:80
    volumes:
     - /sessions
